"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Dungeon of the Night Shade.py']
DATA_FILES = [('', ['images']), ('', ['sound']), ('', ['music'])]
OPTIONS = {
        'iconfile':'icon.icns',
        'packages':['pygame', 'os', 'random']
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
